### ISSUE TITLE
Option to mute webhook

### ISSUE THREAD

**Issue by yooksi** [Trello-Bot-Community/TrelloBot#1]
I have originally made this [request](https://discordapp.com/channels/224068555648270337/260994666319577088/611179328616660992) on **Trello Enthusiasts Club** Discord server.

The current way to accomplish completely muting the webhook is by pinning the command to set (add/remove) custom webbits configuration and another one to remove all the webbits then just copy/pasting them to act like control on/off switches. However this is not an ideal approach.

Having custom webbit presets which users could create, edit and remove with use of bot commands would be a really great addition to the bot and would increase the level of configuration possibilities the software holds.

**Comment by Yamboy1** [comment]
Mute commandsadded in #19 :+1:

**Comment by Yamboy1** [comment]
Also see Trello-Bot-Community/TrelloWebhookAPI#2
