### ISSUE TITLE
serverwebhooks command

### ISSUE THREAD

**Issue by Yamboy1** [Trello-Bot-Community/TrelloBot#12]
Gets all of the webhooks for the server that you're in, in a nice format,

e.g. `Webhook Name - Channel - <Webhook URL>`

**Comment by Yamboy1** [comment]
Scrapping this idea, won't be useful anymore

**Comment by Snazzah** [comment]
This is actually in the rewrite https://github.com/trello-talk/TrelloBot/commit/5890e54ae77984a8fd4ac65ea743be0b87628178
