### ISSUE TITLE
Make scroll pages permanent visible / use

### ISSUE THREAD

**Issue by FAMossu** [Trello-Bot-Community/TrelloBot#7]
The scroll page is suddenly dissapeared. It's happen on `T!viewlist`, probably this happen on other function.
![Screenshot_2019-09-21-23-43-17-749_com discord](https://user-images.githubusercontent.com/39128490/65376423-c600f700-dcc9-11e9-8318-98e94090d639.png)

**Comment by FAMossu** [comment]
sorry, miswritten
i mean the arrow navigation to next pages

**Comment by Yamboy1** [comment]
Arrow Navigation still works, your bot probably doesn't have `Add Reactions` permissions. The default invite currently doesn't give this permission, so you'll need to give this to the bot manually.

I will close this issue once the default invite is changed

**Comment by Yamboy1** [comment]
Fixed
